//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fasr_n_Furious
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int info_id { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public Nullable<int> age { get; set; }
        public string sex { get; set; }
        public string country { get; set; }
        public int user_id { get; set; }
    
        public virtual User User { get; set; }
    }
}
